language: node_js
node_js: 
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run webdriver-update
  - npm run webdriver-start > /dev/null &
  - sleep 2 # give server time to start
  - node_modules/ionic/bin/ionic serve --nolivereload &
  - git clone https://github.com/makinacorpus/phenology-backend.git
  - cd ./phenology-backend
  - python bootstrap.py -c buildout.cfg
  - ./bin/buildout -Nv
  - sh ./resetDb.sh
  - python ./bin/django-admin.py runserver 0.0.0.0:8000 &
  - cd ..
  - node_modules/protractor/bin/protractor test/protractor.conf.js --browser=firefox